export default
[{
      name    : 'clear-day',
      image   : 'clear-day.webp',
      place   : 'center left',
      credit  : 'Elia Clerici',
      profile : 'https://unsplash.com/@ielix',
      site    : 'Unsplash',
      link    : 'https://unsplash.com/photos/XIrIWKCQykg',
      text    : '#EDF8FD',
      title   : '#B1E4FB',
      accent  : '#78D5F7',
      item    : '#1571B7',
      shadow  : '#0A3670'
}, {
      name    : 'clear-night',
      image   : 'clear-night.webp',
      place   : 'bottom center',
      credit  : 'Jeremy Thomas',
      profile : 'https://unsplash.com/@jeremythomasphoto',
      site    : 'Unsplash',
      link    : 'https://unsplash.com/photos/E0AHdsENmDg',
      text    : '#F6F9F7',
      title   : '#D0D6F1',
      accent  : '#C9BBDD',
      item    : '#122E4F',
      shadow  : '#11202D'
}, {
      name    : 'clouds',
      image   : 'clouds.webp',
      place   : 'bottom left',
      credit  : 'Wayne Low',
      profile : 'https://unsplash.com/@wayneshin',
      site    : 'Unsplash',
      link    : 'https://unsplash.com/photos/kJNOYBetxh0',
      text    : '#F5F5F4',
      title   : '#FEE7D8',
      accent  : '#E9C1AF',
      item    : '#7F9BAA',
      shadow  : '#526575'
}, {
      name    : 'drizzle',
      image   : 'drizzle.webp',
      place   : 'top right',
      credit  : 'Mario Calvo',
      profile : 'https://unsplash.com/@mariocalvo',
      site    : 'Unsplash',
      link    : 'https://unsplash.com/photos/VR0s3Yqm2RA',
      text    : '#FCFBFB',
      title   : '#B8CBF4',
      accent  : '#ECDACA',
      item    : '#865E48',
      shadow  : '#1F303A'
}, {
      name    : 'rain',
      image   : 'rain.webp',
      place   : 'top left',
      credit  : 'Jessica Knowlden',
      profile : 'https://unsplash.com/@mybibimbaplife',
      site    : 'Unsplash',
      link    : 'https://unsplash.com/photos/tFLp4a_7aP0',
      text    : '#F6F8F7',
      title   : '#FCF2AE',
      accent  : '#8DDDE2',
      item    : '#45595F',
      shadow  : '#313031'
}, {
      name    : 'storm',
      image   : 'storm.webp',
      place   : 'center center',
      credit  : 'Debasish Vishal',
      profile : 'https://www.pexels.com/@debasish-vishal-2516081',
      site    : 'Pexels',
      link    : 'https://www.pexels.com/photo/scenic-view-of-a-lightning-in-the-sky-4124167/',
      text    : '#FBFAF9',
      title   : '#C08ED7',
      accent  : '#E77EA2',
      item    : '#152668',
      shadow  : '#191945'
}, {
      name    : 'snow',
      image   : 'snow.webp',
      place   : 'center right',
      credit  : 'Aaron Burden',
      profile : 'https://unsplash.com/@aaronburden',
      site    : 'Unsplash',
      link    : 'https://unsplash.com/photos/5AiWn2U10cw',
      text    : '#DAF1FE',
      title   : '#C5D9EC',
      accent  : '#90AAC4',
      item    : '#5C5F65',
      shadow  : '#25221B'
}, {
      name    : 'haze',
      image   : 'haze.webp',
      place   : 'bottom center',
      credit  : 'Maxim Medvedev',
      profile : 'https://unsplash.com/@medvedevmax',
      site    : 'Unsplash',
      link    : 'https://unsplash.com/photos/87dFRyIoIYk',
      text    : '#F1E6E4',
      title   : '#D5B4AE',
      accent  : '#FE7297',
      item    : '#694F5E',
      shadow  : '#263140'
}, {
      name    : 'wind',
      image   : 'wind.webp',
      place   : 'bottom center',
      credit  : 'Sander Weeteling',
      profile : 'https://unsplash.com/@sanderweeteling',
      site    : 'Unsplash',
      link    : 'https://unsplash.com/photos/iGDg_f_mlWo',
      text    : '#FAF9F7',
      title   : '#E6D0C0',
      accent  : '#8BB2BB',
      item    : '#533D3C',
      shadow  : '#221C1C'
}]
/*

*/